services:
  app:
    image: drorganvidez/evidentia:latest
    container_name: evidentia_app_container
    restart: unless-stopped
    volumes:
      - ../.env:/var/www/html/.env
      - ../storage:/var/www/html/storage
      - ../scripts:/www/html/scripts
    expose:
      - "9000"
    depends_on:
      - mysql
      - redis
    env_file:
      - ../.env
    networks:
      - evidentia_net

  mysql:
    image: mysql:8
    container_name: evidentia_mysql_container
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "${DB_FORWARD_PORT:-3307}:3306"
    volumes:
      - db_data_prod:/var/lib/mysql
    networks:
      - evidentia_net

  redis:
    image: redis:7
    container_name: evidentia_redis_container
    restart: unless-stopped
    networks:
      - evidentia_net

  nginx:
    image: nginx:alpine
    container_name: evidentia_nginx_container
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ../:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - evidentia_net

  watchtower:
    container_name: evidentia_watchtower_container
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 120 evidentia_app_container
    restart: unless-stopped
    networks:
      - evidentia_net

volumes:
  db_data_prod:

networks:
  evidentia_net:
