services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: evidentia_app_container_prod
    volumes:
      - ../:/var/www/html
    ports:
      - "${APP_PORT:-9000}:9000"
    depends_on:
      - mysql
      - redis
    env_file:
      - ../.env
    entrypoint: ["sh", "/var/www/html/docker/entrypoint.prod.sh"]

  mysql:
    image: mysql:8
    container_name: evidentia_mysql_container_prod
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "${DB_FORWARD_PORT:-3307}:3306"
    volumes:
      - db_data_prod:/var/lib/mysql

  redis:
    image: redis:7
    container_name: evidentia_redis_container_prod
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db_data_prod:
